src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>switzerland</fullName>
                    <label>Switzerland</label>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PermanentCountry__c</fullName>
        <label>Country</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermanentPostalZipCode__c</fullName>
        <label>Postal/Zip Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonalCity__c</fullName>
        <label>City</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Permanent Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/University__c.object
<CustomObject>
    <fields>
        <fullName>Bonus_Amount_2__c</fullName>
        <label>Bonus Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bonus_Amount__c</fullName>
        <label>Bonus Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bonus_Description_1__c</fullName>
        <label>Bonus Description 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bonus_Description_2__c</fullName>
        <label>Bonus Description 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commision_Rate_Type__c</fullName>
        <label>Commision Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Per Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commision_Rate_Year_01__c</fullName>
        <label>Commission Rate Year 01</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency_Type__c</fullName>
        <label>University Currency Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AED</fullName>
                </value>
                <value>
                    <fullName>AFN</fullName>
                </value>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>AMD</fullName>
                </value>
                <value>
                    <fullName>ANG</fullName>
                </value>
                <value>
                    <fullName>AOA</fullName>
                </value>
                <value>
                    <fullName>ARS</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>AWG</fullName>
                </value>
                <value>
                    <fullName>AZN</fullName>
                </value>
                <value>
                    <fullName>BAM</fullName>
                </value>
                <value>
                    <fullName>BBD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>BGN</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BIF</fullName>
                </value>
                <value>
                    <fullName>BMD</fullName>
                </value>
                <value>
                    <fullName>BND</fullName>
                </value>
                <value>
                    <fullName>BOB</fullName>
                </value>
                <value>
                    <fullName>BRL</fullName>
                </value>
                <value>
                    <fullName>BSD</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
                <value>
                    <fullName>BWP</fullName>
                </value>
                <value>
                    <fullName>BYN</fullName>
                </value>
                <value>
                    <fullName>BZD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CDF</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>CLP</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DoPaymentAfterVisa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Payment After Visa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReady__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Students_Per_Bonus_Amount_2__c</fullName>
        <label>Number of Students Per Bonus Amount 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Students_Per_the_Bonus_Amount__c</fullName>
        <label>Number of Students Per Bonus Amount 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>University</label>
    <nameField>
        <label>University Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Universities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CD_WOD_MassEmailControllerTest.cls
@isTest
public class CD_WOD_MassEmailControllerTest 
{
    @testSetup
    public static void setup(){
        University__c   univ = new University__c(Name ='University 1',DoPaymentAfterVisa__c = True,IsReady__c = True,Currency_Type__c	= 'AFN'
                                                 ,Commision_Rate_Type__c = 'Percentage',Commision_Rate_Year_01__c = 100,Bonus_Amount__c = 1000,Bonus_Amount_2__c = 2000
                                                 ,Number_of_Students_Per_the_Bonus_Amount__c = 1,Bonus_Description_1__c = 'Per Head Bonus (PHB)'
                                                 ,Number_of_Students_Per_Bonus_Amount_2__c = 1,Bonus_Description_2__c = 'Per Head Bonus (PHB)');       
        Insert univ;        
        
        Account acc = new Account(Name ='Student ', Last_Name__c = 'Last',Email__c = 'Example@gmail.com',
                                  Mobile__c = '9003036399',Gender__c = 'Female',Marital_Status__c = 'Single',Date_of_Birth__c = date.parse('09/07/1985'),
                                  City__c = 'Los Angeles',Country_Interested_In__c = 'Australia',Interested_Field_of_Study__c = 'Aeronautics',
                                  Address_Line_1__c = '7885 Mockingbird Hill',PersonalCity__c = 'Oakland',PermanentCountry__c = 'United States',PermanentPostalZipCode__c = 'E4T H6T',
                                  Sic = '2019',Preferred_University__c = univ.Id);        
        Insert acc;
        
        Campaign cmp = new Campaign();
        cmp.Name = 'Test Campaign';
        cmp.StartDate = Date.valueOf('2020-08-20');
        insert cmp;
        
        Lead__c L = new Lead__c();
        l.name = 'Test';
        l.Last_Name__c = 'Last test';
        l.Email__c  = 's23@gmail.com';
        l.Mobile__c = '9087967543';
        l.Web_Lead_Subject__c = 'Test Subject';
        l.Web_Lead_Message__c = 'Test Message';
        l.Preferred_University__c = null;
        l.Lead_Source__c = 'Friend';
        l.Campaign_Email_Triggered__c = true;
        l.Campaign__c = cmp.Id;
        INSERT l;       
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Sample PDF';
        cv.ContentUrl = 'google.com/item';
        insert cv; 
        
        Mass_Email_Addresses__c me = new Mass_Email_Addresses__c();
        me.Name = CD_WOD_MassEmail_Util.CD_FROM_EMAIL_HELLO;
        me.Email_Value__c = 'suresh@cduk.lk';
        insert me;
        
        System.runAs (new User(Id = UserInfo.getUserId()) ){
            EmailTemplate validEmailTemplate = new EmailTemplate();
            validEmailTemplate.isActive = true;
            validEmailTemplate.Name = 'Test Template';
            validEmailTemplate.DeveloperName = 'sample_template_for_testing';
            validEmailTemplate.TemplateType = 'custom';
            validEmailTemplate.FolderId = UserInfo.getUserId();     
            validEmailTemplate.HtmlValue = '{!Lead__c.Name} - {!Account.Name} - {!Campaign.Name}';
            validEmailTemplate.Subject = 'Test Subject';
            insert validEmailTemplate;
        }
        
    }
    
    @isTest
    public static void TestMethod_Success(){
        test.startTest();
        List<CD_WOD_MassEmailController.CampaignWrapper> cwrap = CD_WOD_MassEmailController.getCampaignList();
        List<EmailTemplate> templates = CD_WOD_MassEmailController.getEmailTemplates();
        
        List<Campaign> camps = [SELECT id FROM Campaign];
        CD_WOD_MassEmailController.JobFeedback feedback = CD_WOD_MassEmailController.sendCampaignReminders(camps.get(0).Id, '2020-09-12T18:13:41Z');
        
        //negative
        CD_WOD_MassEmailController.JobFeedback feedback_exp = CD_WOD_MassEmailController.sendCampaignReminders(camps.get(0).Id, null);
        
        List<ContentVersion> files =  CD_WOD_MassEmailController.getExistingFiles();
        test.stopTest();
    }
    
    @isTest
    public static void TestMethod_Schedule(){
        test.startTest();        
        List<Campaign> camps = [SELECT id FROM Campaign];
        String cron_trigger =  CD_WOD_MassEmail_Util.getCronTrigger('2020-09-12T18:13:41Z');           
        CD_WOD_SendCampaignReminder massEmail = new CD_WOD_SendCampaignReminder();   
        massEmail.campaignId = camps.get(0).Id;
        String returnString = system.schedule('Mass Email Reminder - ' + camps.get(0).Id, cron_trigger, massEmail);        
        test.stopTest();
    } 
    
    @isTest
    public static void TestMethod_SendNewsLetter(){
        test.startTest();
        List<Campaign> camps = [SELECT id FROM Campaign];
        List<Account> accs = [SELECT id FROM Account];
        List<Lead__c> leads = [SELECT id FROM Lead__c];
        List<EmailTemplate> template = [SELECT Id,DeveloperName,FolderId FROM EmailTemplate WHERE Name = 'Test Template'];
        system.debug('template info ::: '+template.get(0).DeveloperName+' : '+template.get(0).FolderId);
        CD_WOD_MassEmailController.JobFeedback feedback_account = CD_WOD_MassEmailController.sendNewsLetters(template.get(0).Id, '2020-09-12T18:13:41Z',accs.get(0).Id,'0');
        CD_WOD_MassEmailController.JobFeedback feedback_leads = CD_WOD_MassEmailController.sendNewsLetters(template.get(0).Id, '2020-09-12T18:13:41Z',leads.get(0).Id,'0');
        
        //Negative
        CD_WOD_MassEmailController.JobFeedback feedback_exp = CD_WOD_MassEmailController.sendNewsLetters(template.get(0).Id, '2020-09-12T18:13:41Z',null,'0');
        test.stopTest();
    }
    
    @isTest
    public static void TestMethod_SendEventReminder(){
        test.startTest();
        List<Campaign> camps = [SELECT id FROM Campaign];
        List<Account> accs = [SELECT id FROM Account];
        List<Lead__c> leads = [SELECT id FROM Lead__c];
        List<EmailTemplate> template = [SELECT Id FROM EmailTemplate WHERE Name = 'Test Template'];
        CD_WOD_MassEmailController.JobFeedback feedback_account = CD_WOD_MassEmailController.sendEventReminders(template.get(0).Id, '2020-09-12T18:13:41Z',accs.get(0).Id,camps.get(0).id);
        CD_WOD_MassEmailController.JobFeedback feedback_leads = CD_WOD_MassEmailController.sendEventReminders(template.get(0).Id, '2020-09-12T18:13:41Z',leads.get(0).Id,camps.get(0).id);
        
        //Negative
        CD_WOD_MassEmailController.JobFeedback feedback_exp = CD_WOD_MassEmailController.sendEventReminders(template.get(0).Id, '2020-09-12T18:13:41Z',null,camps.get(0).id);
        test.stopTest();
    }
    
    @istest
    public static void TestMethod_VCF_ProcessLeadRecords(){
        test.startTest();
        List<Lead__c> leads = [SELECT id FROM Lead__c];
        ApexPages.StandardSetController std = new ApexPages.StandardSetController(leads);
        VCF_ProcessLeadRecords vcf = new VCF_ProcessLeadRecords(std);
        
        PageReference pg = vcf.redirectToLC();
        test.stopTest();
    }
    
    @istest
    public static void TestMethod_VCF_ProcessAccRecords(){
        test.startTest();
        List<Account> accs = [SELECT id FROM Account];
        ApexPages.StandardSetController std_acc = new ApexPages.StandardSetController(accs);
        VFC_ProcessAccRecords vcf = new VFC_ProcessAccRecords(std_acc);
        
        PageReference pg = vcf.redirectToLC();
        test.stopTest();
    }
}