src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Campaign_List__mdt.object
<CustomObject>
    <description>this mdt will be used to store all campaigns and its related vf version</description>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <inlineHelpText>Please enter the correct Campaign Name. [Hint : copy and paste the campaign name and remove whitespaces]</inlineHelpText>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Version__c</fullName>
        <inlineHelpText>Page version has to be matched with the site-visualforce page version to capture correct campaign</inlineHelpText>
        <label>Page Version</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>V1</fullName>
                    <default>true</default>
                    <label>V1</label>
                </value>
                <value>
                    <fullName>V2</fullName>
                </value>
                <value>
                    <fullName>V3</fullName>
                </value>
                <value>
                    <fullName>V4</fullName>
                </value>
                <value>
                    <fullName>V5</fullName>
                </value>
                <value>
                    <fullName>V6</fullName>
                </value>
                <value>
                    <fullName>V7</fullName>
                </value>
                <value>
                    <fullName>V8</fullName>
                </value>
                <value>
                    <fullName>V9</fullName>
                </value>
                <value>
                    <fullName>V10</fullName>
                </value>
                <value>
                    <fullName>V100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Campaign List</label>
    <pluralLabel>Campaign Lists</pluralLabel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Email_Triggered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Campaign Email Triggered?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Email_Triggered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field will be checked when an email alert is sent by a campaign. So default WF rule email alert won&apos;t be sent</description>
        <label>Campaign Email Triggered?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <description>This field will be used in email templates.</description>
        <formula>Campaign__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Name of the current campaign the Lead belongs to</inlineHelpText>
        <label>Campaign Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Number__c</fullName>
        <label>Home Phone Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CD_WOD_WebToLeadServiceController.cls
/**************************************************************
* Description       : Controller class for CD_WOD_WebToLead: with EmailServicesUtil added
* @author           : Lahiru Subasinghe
* @since            : February 17, 2018
***************************************************************/

public class CD_WOD_WebToLeadServiceController  {
    
    public String firstName { get; set; }
    public String lastName { get; set; }
    public String emailAddress { get; set; }
    public String mobile { get; set; }
    public String infoTextArea { get; set; }
    public String homePhoneNumber { get; set; } 
    public String studyArea { get; set; }    
    public String preferredCountry { get; set; }
    public String hearUs { get; set; }
    public String vfPageNumber { get; set; }
    
    public String selectedMethod { get; set; }
    
    public String errorMsg { get; set; }
    public Boolean showError { get; set; }
    public Boolean showSuccess { get; set; }
    
    //Email related fields
    public String vfVersion { get; set; } 
    public String campaignName;
    public String studentName;
    public DateTime startDate;
    public String duration;
    public String eventLocation;
    
    Map<Id, List<Lead__c>> campToLeadMap = new Map<Id, List<Lead__c>>();
    Map<Id, Campaign> campMap = new Map<Id, Campaign>();
    List<Lead__c> leadList = new List<Lead__c>();
    CD_EmailServicesUtil utilClass = new CD_EmailServicesUtil();
    
    public CD_WOD_WebToLeadServiceController(){
        this.showError = false;
        this.showSuccess = false;
        this.errorMsg = '';
    }
    
    //Add options to selected methods
    public List<SelectOption> getPrefOptions() {
         
        List<SelectOption> options = new List<SelectOption>();
            
        Schema.DescribeFieldResult fieldResult = Lead__c.Country_Interested_In__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        //ops.add(new SelectOption('', '--Select--'));
        for (Schema.PicklistEntry f : ple){
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        
        
        return options; 
    }
    
    
    
    //Add options to hear about us
    public List<SelectOption> getHearAbtUs() {
         
        List<SelectOption> opts = new List<SelectOption>();
            
        Schema.DescribeFieldResult fieldResult = Lead__c.Lead_Source__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        system.debug('=====> ple'+ple);
        
        opts.add(new SelectOption('', '--Select--'));
        for (Schema.PicklistEntry f : ple){
            opts.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        
        system.debug('====> opts'+opts);
        return opts; 
    }
    
   
    
    //Create new Lead
    public void saveLead(){
    
        try{
            
            //Get organization wide address
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'suresh@cduk.lk'];
            
            
            this.vfVersion = 'v1';
                
            Campaign_List__mdt clm = [Select Id, Campaign_Name__c, Page_Version__c From Campaign_List__mdt Where Page_Version__c =:vfVersion];
            Campaign camRec;
            system.debug('====> clm '+clm);
                
            if (clm != null){
                
                camRec = [Select Id, Name, StartDate, EndDate, Duration__c, Location__c From Campaign Where Name =:clm.Campaign_Name__c ];
                this.campaignName = camRec.Name;
                this.startDate = camRec.StartDate;
                this.duration = camRec.Duration__c;
                this.eventLocation = camRec.Location__c;
                
                campMap.put(camRec.Id, camRec);
            }
            
            if (processValidations(camRec, this.emailAddress)){
            
                //First create a lead record and send the email with QR Code
                System.debug('preferredCountry::'+preferredCountry);
                String finalPrefCountryString = '';
                //Prepare preferred Country mpl
                if (preferredCountry != '' && preferredCountry.contains(','))
                    finalPrefCountryString = preferredCountry.substringBetween('[',']').replace(',', ';');
                else if (preferredCountry != '')
                    finalPrefCountryString = preferredCountry.substringBetween('[',']');
                    
                    
                system.debug('finalPrefCountryString'+finalPrefCountryString);
                
                Lead__c aLead = new Lead__c();
                aLead.First_Name__c = firstName;
                aLead.Last_Name__c = lastName;
                aLead.Email__c = emailAddress;
                aLead.Mobile__c = mobile;
                aLead.Home_Phone_Number__c = homePhoneNumber;
                aLead.Interested_Field_of_Study__c = studyArea;
                aLead.Lead_Source__c = hearUs;
                aLead.Campaign_Email_Triggered__c = true;
                if (camRec != null)
                    aLead.Campaign__c = camRec.Id;
                if (finalPrefCountryString != '')
                    aLead.Country_Interested_In__c = finalPrefCountryString;
                aLead.Comments__c = infoTextArea;
                
                insert aLead;
                
                //Implemented this for bulk operations. However here we are pretty sure that Leads comes individually
                leadList.add(aLead);
                campToLeadMap.put(camRec.Id, leadList);
                
                //Load necesary fields to send the email if Lead creation is successfull 
                
                System.debug('====> campMap:: '+campMap);
                System.debug('====> campToLeadMap:: '+campToLeadMap);
                
                List<EmailServiceDTO> esList = prepareEmailServiceWrapper(campMap, campToLeadMap);
                System.debug('====> esList:: '+esList);
                
                utilClass.CD_sendEmails(esList);
                    
                clearForm();
                this.showSuccess = true;
                
                
            }
            
        }catch(exception ex){
            System.debug('EX message::'+ex.getMessage());
            this.errorMsg = 'There are some issues submitting the form. '+ex.getMessage();
            this.showError = true;
            
        }
      
    }
    
    //Process Lead validations
    public Boolean processValidations(Campaign cmp, String email){
        
        //Email validation
        //List<Lead__c> leads = [Select Id, Name, Email__c, Campaign__c From Lead__c Where Campaign__c =:cmp.Id AND Email__c =:email];
        List<Lead__c> leads = [Select Id, Name, Email__c, Campaign__c From Lead__c Where Email__c =:email];
        
        if (leads.size() > 0){
            throw new applicationException('A Lead Student was already created for the same Email');
            //this.errorMsg = 'A Student record was already created for this email address. Please use different email or contact us!';
            //this.showError = true;
            return false;
        }
        else
            return true;
    }
    
    
    //Clears content
    public void clearForm(){
        
        this.firstName = '';
        this.lastName = '';
        this.mobile = '';
        this.emailAddress = '';
        this.infoTextArea = '';
        this.selectedMethod = '--Select--';
        this.preferredCountry = '';
        this.hearUs = '';
        this.homePhoneNumber = '';
    }
   
    
    public void closeNotification(){
        this.showError = false;
        this.showSuccess = false;
    }
    
    public class applicationException extends Exception {}
    
    public List<EmailServiceDTO> prepareEmailServiceWrapper(Map<Id, Campaign> cmpMap, Map<Id, List<Lead__c>> campToLdMap){
        
        List<EmailServiceDTO> esList = new List<EmailServiceDTO>();
        EmailServiceDTO es;
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'suresh@cduk.lk'];
        
        for (Id cmpId: cmpMap.keyset()){
            for (Lead__c ld: campToLdMap.get(cmpId)){
                es = new EmailServiceDTO();
                es.campaignName = cmpMap.get(cmpId).Name;
                es.campaignLocation = cmpMap.get(cmpId).Location__c;
                es.campaignDuration = cmpMap.get(cmpId).Duration__c;
                es.campaignStartDate = cmpMap.get(cmpId).StartDate;
                es.leadRecord = ld;
                es.emailTo = new List<String>{ ld.Email__c };
                
                if ( owea.size() > 0 ) {
                    es.emailFromId = owea.get(0).Id;
                } 
                
                esList.add(es);
            }
        }
        
        return esList;
    } 
    
    

}