src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Virtual_Meeting_Info__c</fullName>
        <inlineHelpText>Please enter the meeting info in a required format</inlineHelpText>
        <label>Virtual Meeting Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadHelper.cls
public class LeadHelper{

    public List<EmailServiceDTO> prepareEmailServiceWrapper(Map<Id, Campaign> cmpMap, Map<Id, List<Lead__c>> campToLdMap){
        
        List<EmailServiceDTO> esList = new List<EmailServiceDTO>();
        EmailServiceDTO es;
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'suresh@cduk.lk'];
        
        for (Id cmpId: cmpMap.keyset()){
            for (Lead__c ld: campToLdMap.get(cmpId)){
                es = new EmailServiceDTO();
                es.campaignName = cmpMap.get(cmpId).Name;
                es.campaignLocation = cmpMap.get(cmpId).Location__c;
                es.campaignDuration = cmpMap.get(cmpId).Duration__c;
                es.campaignStartDate = cmpMap.get(cmpId).StartDate;
                es.campaignVirtualInfo = cmpMap.get(cmpId).Virtual_Meeting_Info__c;
                es.campaignEndDate = cmpMap.get(cmpId).EndDate;
                es.leadRecord = ld;
                es.emailTo = new List<String>{ ld.Email__c };
                
                if ( owea.size() > 0 ) {
                    es.emailFromId = owea.get(0).Id;
                } 
                
                esList.add(es);
            }
        }
        
        return esList;
    } 
}