src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Student</fullName>
                </value>
                <value>
                    <fullName>Follow up Student</fullName>
                </value>
                <value>
                    <fullName>Visa Guidance</fullName>
                </value>
                <value>
                    <fullName>Visa Submission</fullName>
                </value>
                <value>
                    <fullName>Open Day UK</fullName>
                </value>
                <value>
                    <fullName>Open Day Australia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_University__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred University</label>
        <referenceTo>University__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Student</fullName>
                </value>
                <value>
                    <fullName>Follow up Student</fullName>
                </value>
                <value>
                    <fullName>Visa Guidance</fullName>
                </value>
                <value>
                    <fullName>Visa Submission</fullName>
                </value>
                <value>
                    <fullName>Open Day UK</fullName>
                </value>
                <value>
                    <fullName>Open Day Australia</fullName>
                </value>
                <value>
                    <fullName>World Education Fair</fullName>
                </value>
                <value>
                    <fullName>Open Day - Canada</fullName>
                </value>
                <value>
                    <fullName>Called by Udhmila</fullName>
                    <isActive>false</isActive>
                    <label>Called by Udhmila</label>
                </value>
                <value>
                    <fullName>Called by Zeina</fullName>
                    <isActive>false</isActive>
                    <label>Called by Zeina</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Preferred_University__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred University</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>University Should be True</errorMessage>
            <filterItems>
                <field>University__c.IsReady__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>University__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Web_Lead_Message__c</fullName>
        <label>Web Lead Message</label>
        <type>TextArea</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/University__c.object
<CustomObject>
    <fields>
        <fullName>University_Address__c</fullName>
        <label>University Address</label>
        <type>TextArea</type>
    </fields>
    <label>University</label>
    <nameField>
        <label>University Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Universities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WebToLead.cls
/* Controller for Web to Lead form using Custom Lead Object
*  Developed By - Naveen
*/

global with sharing class WebToLead{
    public string LeadType { get;set; }
     
	Map<String , Lead__c> ldmap {get; set;}
    //Added by Lahiru
    public static String preferredCountry { get; set; }
	
    Public Lead__c ld { get; set; }
    public WebToLead(ApexPages.StandardController controller){
        ld = new Lead__c();
        getpickvalues();
        getPrefOptions();
        
        LeadType = Apexpages.currentPage().getParameters().get('leadtype');
	
		
        
    }
    
    /*    
    public static List<SelectOption> getPrefOptions() {
         
        List<SelectOption> options = new List<SelectOption>();
            
        Schema.DescribeFieldResult fieldResult = Lead__c.Country_Interested_In__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        //ops.add(new SelectOption('', '--Select--'));
        for (Schema.PicklistEntry f : ple){
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        
        
        return options; 
    }
	*/
    
    
    
    public list<String> leadSourceList { get;set; }
    public list<String> prefCountryList { get; set; }
    
    /* Get How did you Hear about us Picklist Values   */
    public void getpickvalues(){
        leadSourceList = new List<String>();
        Schema.DescribeFieldResult leadSource = Lead__c.Lead_Source__c.getDescribe();
        List<Schema.PicklistEntry> leadSourceVal = leadSource.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : leadSourceVal) {
            leadSourceList.add(pickListVal.getLabel());
        }   
    }
    
    //Added by Lahiru
    public void getPrefOptions(){
        prefCountryList = new List<String>();
        Schema.DescribeFieldResult prefCoun = Lead__c.Country_Interested_In__c.getDescribe();
        List<Schema.PicklistEntry> prefCountryeVal = prefCoun.getPicklistValues();
        for (Schema.PicklistEntry pickListVal : prefCountryeVal) {
            prefCountryList.add(pickListVal.getLabel());
        }   
    }
    
    
    /*public PageReference receiveInput() {
		 String input1 = Apexpages.currentPage().getParameters().get('input1');
			ldmap.put(input1 , new Lead__c());
			return null;

		}

		public PageReference removeInput() {
        String input2 = Apexpages.currentPage().getParameters().get('input2');
        ldmap.remove(input2);
        return null;
    }*/  
		
	
	
    
    
    
     /* Wrapper  Class For Universities Lookup*/
    public class University {
        public String id;
        public String label;
        public String metaLabel;
        
        public University( String id, String label, String metaLabel ) {
            this.id         = id;
            this.label      = label;
            this.metaLabel  = metaLabel;
        }
        
        public University( University__c  UniversityRecord ) {
            id          = UniversityRecord.Id;
            label       = UniversityRecord.Name;
            metaLabel   = UniversityRecord.University_Address__c;
        }
    }
    
    /*
    @RemoteAction
    public static List<University> getExistingUniversities() {
        List<University__c> universityList = [
            SELECT      Id
                        ,Name
                        ,University_Address__c
            FROM        University__c
        ];
        
        if( universityList != NULL ) {
            List<University> allUniversities = new List<University>();
            for( University__c univVal : universityList ) {
                University univ = new University( univVal );
                allUniversities.add( univ );
            }
            
            return allUniversities;
        }
        
        return NULL;
    }
	/*
   
    /* Save Part */
    @RemoteAction
    global static String saveFormLd( String firstName, String lastName, String email,String mobile,String message,String university,String leadSource,String leadtype, String prefcountry) {
        try {
            Lead__c ld = new Lead__c();
            ld.First_Name__c = firstName;
            ld.Last_Name__c = lastName;
            ld.Email__c =  email;
            ld.Mobile__c = mobile;
            ld.Web_Lead_Message__c = message;
            ld.Preferred_University__c = university;
            ld.Lead_Source__c = leadSource;
            ld.Lead_Type__c = leadtype;
            
            system.debug(':: preferredCountry :: '+prefcountry);
            
            //Add preferred country
            String finalPrefCountryString = '';
            //Prepare preferred Country mpl
            if (prefcountry != '' && prefcountry.contains(','))
                finalPrefCountryString = prefcountry.substringBetween('[',']').replace(',', ';');
            else if (prefcountry != '')
                finalPrefCountryString = prefcountry.substringBetween('[',']');    
            
            ld.Country_Interested_In__c = finalPrefCountryString;
           
            INSERT ld;
        }
        catch(Exception e){
            System.debug('Query Issue:' +e);
        }
        
        return NULL;
    }
}