src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <description>This field will be used in email templates.</description>
        <formula>Campaign__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Name of the current campaign the Lead belongs to</inlineHelpText>
        <label>Campaign Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Initiated_Sources__c</fullName>
        <label>Lead Initiated Sources</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Undecided</fullName>
                </value>
                <value>
                    <fullName>Not Reachable</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Not Converted</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Deactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MainLeadTriggerHandler.cls
public  class MainLeadTriggerHandler {
    
    List<String> emailList = new List<String>();
    List<User> usList = [Select id, name, email, username From user where username='suresh@cduk.lk'];
    
    //public void OnAfterInsert(List<Lead__c> newList, Map<Id, Lead__c> oldMap, Map<Id, Lead__c> newMap){
    public void OnAfterInsert(List<Lead__c> newList, Map<Id, Lead__c> newMap){
    
        for (Lead__c ld: newList){
            emailList.add(ld.Email__c);
           // ld.addError('test error');
        }       
        
        Map<ID, Lead__c> leadWithSameEmailMap = new Map<ID, Lead__c>([Select Id, Email__c, Lead_Status__c, Lead_Initiated_Sources__c, Campaign_Name__c, Lead_Source__c, CreatedDate, OwnerId From Lead__c Where Email__c IN: emailList order by createddate ASC]);
        
        Map<String, List<Lead__c>> emailToLeadMap = new Map<String, List<Lead__c>>();
        List<Lead__c> leadList = new List<Lead__c>();
        
        for (Lead__c ld: leadWithSameEmailMap.values()){
            
            List<Lead__c> emailToLeadList = emailToLeadMap.get(ld.Email__c);
            if (emailToLeadList == null){
                emailToLeadList = new List<Lead__c>();
            }
            
            emailToLeadList.add(ld);            
            emailToLeadMap.put(ld.Email__c, emailToLeadList);
        }
        
        system.debug('emailToLeadMap keyset::::'+emailToLeadMap.keySet());
        system.debug('emailToLeadMap values::::'+emailToLeadMap.values());
        List<Lead__c> leadRecordsToUpdate = new List<Lead__c>();
        List<Lead__c> leadRecordsToDelete = new List<Lead__c>();
        Set<String> leadSourceSet;
        List<String> finalLeadSourceList;
        List<String> leadSourceList = new List<String>();
        Lead__c preferredLead;
       
        
        for (String eml: emailToLeadMap.keySet()){  
            
            leadSourceSet = new Set<String>();
            finalLeadSourceList = new List<String>();
            //preferredLead = new Lead__c();
            integer ldCount=0;
           
            
            if (emailToLeadMap.get(eml).size() > 1){
                for (Lead__c ld: emailToLeadMap.get(eml)){
                    
                    ldCount++;
                    
                    if (ld.Lead_Initiated_Sources__c != '' && ld.Lead_Initiated_Sources__c != null){
                        leadSourceSet.addAll(ld.Lead_Initiated_Sources__c.split(' ::: '));
                    }
                    
                    system.debug('leadSourceSet1::'+leadSourceSet);
                    
                    if (ld.Campaign_Name__c != '' && ld.Campaign_Name__c != null){
                        leadSourceSet.add(ld.Campaign_Name__c);
                        //finalLeadSourceList.add(ld.Campaign_Name__c);
                    }else if (ld.Lead_Source__c != '' && ld.Lead_Source__c != null){
                        leadSourceSet.add(ld.Lead_Source__c);
                        //finalLeadSourceList.add(ld.Lead_Source__c);
                    }
                    
                    if (ld.Lead_Status__c != 'New' && preferredLead == null){                        
                        preferredLead = ld;
                        
                    }else{
                        if (emailToLeadMap.get(eml).size() == ldCount && preferredLead == null){
                            preferredLead = ld;
                            
                        }else{
                        	leadRecordsToDelete.add(ld);
                        }
                    }
                }
            }    
            
            system.debug('leadSourceList:::'+leadSourceSet);
            system.debug('leadSourceSet:::'+leadSourceSet);
            
            if (!leadSourceSet.isEmpty()){
                
                leadSourceList.addAll(leadSourceSet);
                preferredLead.Lead_Initiated_Sources__c = string.join(leadSourceList,' ::: ');
                preferredLead.OwnerId = usList[0].Id;
                leadRecordsToUpdate.add(preferredLead);
            }
			
            
            system.debug('leadRecordsToUpdate:::'+leadRecordsToUpdate);
            system.debug('leadRecordsToDelete:::'+leadRecordsToDelete+':::count::'+leadRecordsToDelete.size());
        }
        
        if (!leadRecordsToDelete.isEmpty()){            
            for (Lead__c dLd: leadRecordsToDelete){ 
                dLd.OwnerId = usList[0].Id;
                dLd.Lead_Status__c = 'Deactivated';                
                leadRecordsToUpdate.add(dLd);
            }
            //delete leadRecordsToDelete;   
        }
        
        if (!leadRecordsToUpdate.isEmpty()){
            upsert leadRecordsToUpdate;
        }
        	
        
        
        	  	
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    

}