src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Student</fullName>
                </value>
                <value>
                    <fullName>Follow up Student</fullName>
                </value>
                <value>
                    <fullName>Visa Guidance</fullName>
                </value>
                <value>
                    <fullName>Visa Submission</fullName>
                </value>
                <value>
                    <fullName>Open Day UK</fullName>
                </value>
                <value>
                    <fullName>Open Day Australia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_University__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred University</label>
        <referenceTo>University__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Student</fullName>
                </value>
                <value>
                    <fullName>Follow up Student</fullName>
                </value>
                <value>
                    <fullName>Visa Guidance</fullName>
                </value>
                <value>
                    <fullName>Visa Submission</fullName>
                </value>
                <value>
                    <fullName>Open Day UK</fullName>
                </value>
                <value>
                    <fullName>Open Day Australia</fullName>
                </value>
                <value>
                    <fullName>World Education Fair</fullName>
                </value>
                <value>
                    <fullName>Open Day - Canada</fullName>
                </value>
                <value>
                    <fullName>Called by Udhmila</fullName>
                    <isActive>false</isActive>
                    <label>Called by Udhmila</label>
                </value>
                <value>
                    <fullName>Called by Zeina</fullName>
                    <isActive>false</isActive>
                    <label>Called by Zeina</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Preferred_University__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred University</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>University Should be True</errorMessage>
            <filterItems>
                <field>University__c.IsReady__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>University__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Web_Lead_Message__c</fullName>
        <label>Web Lead Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Web_Lead_Subject__c</fullName>
        <label>Web Lead Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/University__c.object
<CustomObject>
    <fields>
        <fullName>University_Address__c</fullName>
        <label>University Address</label>
        <type>TextArea</type>
    </fields>
    <label>University</label>
    <nameField>
        <label>University Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Universities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/WebToLeadTest.cls
/*

Created By :- Arulmozhi.R
Description:- Test Class for Web to Lead Form

Lahiru : Updating the test classes due to lack of coverage by Dazework

*/

@isTest
public class WebToLeadTest {
    
    
    static testMethod void MyTest()
    {
        
        
        Lead__c L = new Lead__c();
        l.name = 'Test';
        l.Last_Name__c = 'Last test';
        l.Email__c  = 's23@gmail.com';
        l.Mobile__c = '9087967543';
        l.Web_Lead_Subject__c = 'Test Subject';
        l.Web_Lead_Message__c = 'Test Message';
        l.Preferred_University__c = null;
        l.Lead_Source__c = 'Friend';
        l.Country_Interested_In__c = 'USA';
        INSERT l;
        
        University__c uRec = new University__c(name='test', University_Address__c='test');
        
        
        //String firstName, String lastName, String email,String mobile,String message,String university,String leadSource
        Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(l);
        WebToLead testWeb = new WebToLead(sc);
        WebToLead.saveFormLd(l.Last_Name__c,l.Name,l.Email__c,l.Mobile__c,l.Web_Lead_Message__c,l.Preferred_University__c,l.Lead_Source__c,l.Lead_Type__c,l.Country_Interested_In__c);
        //WebToLead.getPrefOptions();
        //WebToLead.getExistingUniversities();
        WebToLead.University un = new WebToLead.University('test', 'test', 'test');
        WebToLead.University un2 = new WebToLead.University(uRec);
        

        
        Test.StopTest();
        
    }
}