src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Nearest_Branch__c</fullName>
        <description>Nearest Branch</description>
        <label>Nearest Branch</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Colombo</fullName>
                </value>
                <value>
                    <fullName>Kandy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Participated?</label>
        <type>Checkbox</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MainLeadTriggerTestClass.cls
@isTest
public class MainLeadTriggerTestClass {
    
    /*
    @testSetup static void setupTestData() {
		
        Profile prof = [select id from profile where name = 'System Administrator'];
        User user = new User();
        user.firstName = 'tFname';
        user.lastName = 'tLName';
        user.profileId = prof.id;
        user.username = 'test@cduk.com.prod';
        user.email = 'test@cduk.com';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.Alias = 'laSubas'; 
        user.TimeZoneSidKey = 'America/Los_Angeles'; 
        user.LocaleSidKey = 'en_US';
        user.LanguageLocaleKey = 'en_US'; 
        insert user;
        
        system.runAs(user){
            Campaign cm = new Campaign();
            cm.name = 'Test Campaign';
            cm.StartDate = Date.parse( '12/17/2019' );
            cm.OwnerId = user.id;
            insert cm;
            
            List<Lead__c> ldList = new List<Lead__c>();
            Lead__c ld;
            ld = new Lead__c();
            ld.Email__c = 'test@test.com';
            ld.Mobile__c = '0772653855';
            ld.First_Name__c = 'fName';
            ld.Last_Name__c = 'lName';
            ld.Lead_Source__c = 'facebook';
            ld.OwnerId = user.id;
            ldList.add(ld);
            
            ld = new Lead__c();
            ld.Email__c = 'test@test.com';
            ld.Mobile__c = '0772653855';
            ld.First_Name__c = 'fName';
            ld.Last_Name__c = 'lName';
            ld.Campaign__c = cm.Id;
            ld.Lead_Source__c = 'Call';
            ld.OwnerId = user.id;
            ldList.add(ld);
            
            
            insert ldList;
        }
        
    }
	*/
    
    /*
    @isTest
    static void processLeadTestMethod_withCounselor(){
        
        String uniqueUserName = 'cduser' + DateTime.now().getTime() + '@cd.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='Counsellor'];
        User u = new User(Alias = 'standt', Email='counsellor@cd.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName=uniqueUserName);
            
            
            
            
            System.runAs(u) {
                
                Test.startTest();
                
                Lead__c ld = [Select Id, Name, Mobile__c, Email__c, Participated__c from Lead__c LIMIT 1];
                
                CD_ProcessLeadController ctrl = new CD_ProcessLeadController();
                PageReference pageRef = Page.processLead;
                test.setCurrentPageReference(pageRef);
                pageRef.getParameters().put('lid',ld.Id);
                System.debug('ld:::'+ld);
                ctrl.updateLeadRecord();
                
                ctrl.showError = false;
                ctrl.showSuccess = false;
                ctrl.errorMsg = '';
                ctrl.email = 'test@test1.com';
                ctrl.phoneNumber = '0772653856';
                
                ctrl.saveLead();
                ctrl.clearForm();
                ctrl.closeNotification();
                Test.stopTest();
            }
            
            
            Lead__c ldRec = [Select Id, Name, Participated__c From Lead__c LIMIT 1];
            System.debug('ldRec ::'+ldRec.Participated__c);
            System.assertEquals(ldRec.Participated__c, true);
    }
    */
    
    @isTest
    static void processLeadTestMethod_withExceptions_saveRecord(){
        
        Test.startTest();
        String uniqueUserName = 'cduser' + DateTime.now().getTime() + '@cd.com';
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='counsellor@cd.com',
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName=uniqueUserName);
        insert u;
        //System.runAs(u) {
            
            Campaign cm = new Campaign();
            cm.name = 'Test Campaign';
            cm.StartDate = Date.parse( '12/17/2019' );
            cm.OwnerId = u.id;
            insert cm;
            
            List<Lead__c> ldList = new List<Lead__c>();
            Lead__c ld;
            ld = new Lead__c();
            ld.Email__c = 'test@test.com';
            ld.Mobile__c = '0772653855';
            ld.First_Name__c = 'fName';
            ld.Last_Name__c = 'lName';
            ld.Lead_Source__c = 'facebook';
            ld.OwnerId = u.id;
            ld.Country_Interested_In__c= 'Australia';
            ld.Nearest_Branch__c = 'Colombo';
            ldList.add(ld);
            
            ld = new Lead__c();
            ld.Email__c = 'test@test.com';
            ld.Mobile__c = '0772653855';
            ld.First_Name__c = 'fName';
            ld.Last_Name__c = 'lName';
            ld.Campaign__c = cm.Id;
            ld.Lead_Source__c = 'Call';
            ld.OwnerId = u.id;
            ld.Country_Interested_In__c= 'Australia';
            ld.Nearest_Branch__c = 'Colombo';
            ldList.add(ld);
            
            
            insert ldList;
            
            
            //List<Lead__c> ld = [Select Id, Name, Mobile__c, Email__c, Participated__c from Lead__c LIMIT 2];
        //}
        
        
        
        /*
        CD_ProcessLeadController ctrl = new CD_ProcessLeadController();
        PageReference pageRef = Page.processLead;
        test.setCurrentPageReference(pageRef);
        
        ctrl.showError = false;
        ctrl.showSuccess = false;
        ctrl.errorMsg = '';
        ctrl.email = 'dummy@test.com';
        ctrl.phoneNumber = '0772653856';
        
        ctrl.saveLead();
		*/
        
        Test.stopTest();
    }
    
    

    
   

}