src/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Permanent Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Permanent Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>Current City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_p__c</fullName>
        <label>City (Permanent)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Interested_In__c</fullName>
        <label>Country Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>New Zealand</fullName>
                </value>
                <value>
                    <fullName>Switzerland</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Grenada</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Belarus - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Russia - Medicine only</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                    <isActive>false</isActive>
                    <label>Latvia</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_p__c</fullName>
        <description>Country for Permanent Address</description>
        <label>Country (Permanent)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Qualification__c</fullName>
        <label>Current Qualification</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Postgraduate</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>HND</fullName>
                </value>
                <value>
                    <fullName>Diploma</fullName>
                </value>
                <value>
                    <fullName>Certificates</fullName>
                </value>
                <value>
                    <fullName>Foundation Course</fullName>
                </value>
                <value>
                    <fullName>A/L</fullName>
                </value>
                <value>
                    <fullName>O/L</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expected_Year_to_Begin__c</fullName>
        <label>Expected Year &amp; Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>How did you Hear About us ?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Paper Advertisement</fullName>
                </value>
                <value>
                    <fullName>Topjobs Advertisement</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Television Advertisement</fullName>
                </value>
                <value>
                    <fullName>Radio Advertisement</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>Leaflet</fullName>
                </value>
                <value>
                    <fullName>Google Ads</fullName>
                </value>
                <value>
                    <fullName>YouTube</fullName>
                </value>
                <value>
                    <fullName>Exhibition</fullName>
                </value>
                <value>
                    <fullName>Other Event</fullName>
                </value>
                <value>
                    <fullName>Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Married</fullName>
                </value>
                <value>
                    <fullName>Divorced</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Zip_Code_p__c</fullName>
        <description>postal code for permanent address</description>
        <label>Postal/Zip Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_University__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred University</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>University Should be True</errorMessage>
            <filterItems>
                <field>University__c.IsReady__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>University__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leads</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/University__c.object
<CustomObject>
    <label>University</label>
    <nameField>
        <label>University Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Universities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FacebookAPI.cls
public with sharing class FacebookAPI {
    //public static final String FACEBOOK_LEADS_ENDPOINT = 'https://graph.facebook.com/v3.1/545322862568323/leads';
    
    public static Map<String, String> fieldMapping {
        get {
            return new Map<String, String> {
                //Custom Details
                'passport_number'               => 'Passport_Number__c'
                ,'how_did_hear_about_us?'       => 'Lead_Source__c'
                ,'expected_year_to_begin'       => 'Expected_Year_to_Begin__c'
                ,'current_qualification'        => 'Current_Qualification__c'
                ,'interested_field_of_study'    => 'Interested_Field_of_Study__c'
                ,'current_city'                 => 'City__c'
                
                //Personal Details
                ,'first_name'                   => 'Name'
                ,'last_name'                    => 'Last_Name__c'
                ,'email'                        => 'Email__c'
                ,'phone_number'                 => 'Mobile__c'
                ,'gender'                       => 'Gender__c'
                ,'marital_status'               => 'Marital_Status__c'
                               
                //Address Details
                ,'street_address'               => 'Address_Line_1__c'
                ,'city'                         => 'City_p__c'
                ,'state'                        => 'Address_Line_2__c'
                ,'country'                      => 'Country_p__c'
                ,'zip_code'                     => 'Postal_Zip_Code_p__c'
            };
        }
    }
    
    @future(callout=true)
    public static void getLeads() {
       
        HttpRequest req = new HttpRequest();
        
        req.setMethod( 'GET' );
        req.setEndpoint('callout:Facebook_Named');
        req.setheader('accept','application/json');
        
        HttpResponse resp = new Http().send( req );
        if( resp.getStatusCode() == 200 ) {
            FacebookClasses.FacebookResponse fbResp = ( FacebookClasses.FacebookResponse ) JSON.deserialize( resp.getBody(), FacebookClasses.FacebookResponse.class );
           
            List<Lead__c> leads = new List<Lead__c>();
            
            Map<String, String> universities = getStoredUniversities();
            
            for( FacebookClasses.Datum datum : fbResp.data ) {
                Lead__c ld = new Lead__c();
                
                for( FacebookClasses.FieldDatum fldDatum : datum.field_data ) {
                    /**
                     * Exception for Country
                     */
                    if( fldDatum.name.startsWith( 'country_interested_in' ) ) {
                        ld.Country_Interested_In__c = String.join( fldDatum.values, '' ).replace( ',', ';' );
                        //ld.Country_Interested_In__c = fldDatum.values[0].replace( ',', ';' );
                    }
                    
                    /**
                     * Exception for DOB
                     */
                    else if( fldDatum.name.equals( 'date_of_birth' ) ) {
                        List<String> parts = new List<String>();
                        parts = String.join( fldDatum.values, '' ).split('/');
                        Date DOB = Date.newInstance(Integer.valueOf(parts[2]), Integer.valueOf(parts[0]), Integer.valueOf(parts[1]));
                        ld.DOB__c = DOB;
                    }
                    
                    /**
                     * Exception for Preferred University
                     */
                    else if( fldDatum.name.equals( 'preferred_university' ) ) {
                        ld.Preferred_University__c = universities.get( String.join( fldDatum.values, '' ) );
                        //ld.Preferred_University__c = universities.get( fldDatum.values[0] );
                    }
                    
                    else {
                        String fieldAPIName = fieldMapping.get( fldDatum.name );
                        ld.put( fieldAPIName, String.join( fldDatum.values, '' ) );
                        //ld.put( fieldAPIName, fldDatum.values[0] );
                    }
                }
                
                ld.Lead_Source__c = 'Facebook';   
                System.debug('The leads is '+leads);
                leads.add( ld );
            }
            
            UPSERT leads Email__c;
        }
        
    }
    
    private static Map<String, String> getStoredUniversities() {
        Map<String, String> storedUniversities = new Map<String, String>();
        
        for( University__c univ : [
                SELECT  Id
                        ,Name
                FROM    University__c
                LIMIT   50000
            ]
        ) {
            storedUniversities.put( univ.Name, univ.Id );
        }
        
        return storedUniversities;
    }
}