src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Current_City__c</fullName>
        <label>Current City</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interested_Field_of_Study__c</fullName>
        <label>Interested Field of Study</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Type__c</fullName>
        <label>Lead Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Student</fullName>
                </value>
                <value>
                    <fullName>Follow up Student</fullName>
                </value>
                <value>
                    <fullName>Visa Guidance</fullName>
                </value>
                <value>
                    <fullName>Visa Submission</fullName>
                </value>
                <value>
                    <fullName>Open Day UK</fullName>
                </value>
                <value>
                    <fullName>Open Day Australia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/DOBFormatTest.cls
@isTest
public class DOBFormatTest {
    static testMethod void MyTest()
    {
        List<Lead> lead = new List<Lead>();
        for (Integer i = 0; i < 1000; i++) {
            lead.add(new Lead(Company = 'Test Lead',
                              LastName = 'Lead Last Name',
                              Date_of_Birth__c = '09/05/1991',
                             Email='abctestOnly@gmail.com',
                             Current_City__c='TestCity',
                             Gender__c='Male',
                             Interested_Field_of_Study__c='TestField',
                             Lead_Type__c='New Student',
                             MobilePhone = '0711111111'));
            
            
        }
        INSERT lead;
    }
}