src/objects/University__c.object
<CustomObject>
    <fields>
        <fullName>Bonus_Amount_2__c</fullName>
        <label>Bonus Amount 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bonus_Amount__c</fullName>
        <label>Bonus Amount 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bonus_Description_1__c</fullName>
        <label>Bonus Description 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bonus_Description_2__c</fullName>
        <label>Bonus Description 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commision_Rate_Type__c</fullName>
        <label>Commision Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Per Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commision_Rate_Year_01__c</fullName>
        <label>Commission Rate Year 01</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency_Type__c</fullName>
        <label>University Currency Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AED</fullName>
                </value>
                <value>
                    <fullName>AFN</fullName>
                </value>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>AMD</fullName>
                </value>
                <value>
                    <fullName>ANG</fullName>
                </value>
                <value>
                    <fullName>AOA</fullName>
                </value>
                <value>
                    <fullName>ARS</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>AWG</fullName>
                </value>
                <value>
                    <fullName>AZN</fullName>
                </value>
                <value>
                    <fullName>BAM</fullName>
                </value>
                <value>
                    <fullName>BBD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>BGN</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BIF</fullName>
                </value>
                <value>
                    <fullName>BMD</fullName>
                </value>
                <value>
                    <fullName>BND</fullName>
                </value>
                <value>
                    <fullName>BOB</fullName>
                </value>
                <value>
                    <fullName>BRL</fullName>
                </value>
                <value>
                    <fullName>BSD</fullName>
                </value>
                <value>
                    <fullName>BTN</fullName>
                </value>
                <value>
                    <fullName>BWP</fullName>
                </value>
                <value>
                    <fullName>BYN</fullName>
                </value>
                <value>
                    <fullName>BZD</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CDF</fullName>
                </value>
                <value>
                    <fullName>CHF</fullName>
                </value>
                <value>
                    <fullName>CLP</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DoPaymentAfterVisa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Payment After Visa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsReady__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Students_Per_Bonus_Amount_2__c</fullName>
        <label>Number of Students Per Bonus Amount 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Students_Per_the_Bonus_Amount__c</fullName>
        <label>Number of Students Per Bonus Amount 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>University</label>
    <nameField>
        <label>University Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Universities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/StudentApplicationClassTest.cls
@isTest
public class StudentApplicationClassTest {
    @isTest static void insertStudentJSONRecords() {
        
        Document documentObj = new Document(Body = Blob.valueOf('Some Document Text'),ContentType = 'application/pdf',DeveloperName = 'my_document'
                                           ,IsPublic = true,Name = 'My Document',FolderId = UserInfo.getUserId());
        Insert documentObj;        
      
        /* For Lookup to University */
        
        University__c   univ = new University__c(Name ='University',DoPaymentAfterVisa__c = True,IsReady__c = True,Currency_Type__c	= 'AFN'
                                                 ,Commision_Rate_Type__c = 'Percentage',Commision_Rate_Year_01__c = 100,Bonus_Amount__c = 1000,Bonus_Amount_2__c = 2000
                                                 ,Number_of_Students_Per_the_Bonus_Amount__c = 1,Bonus_Description_1__c = 'Per Head Bonus (PHB)'
                                                 ,Number_of_Students_Per_Bonus_Amount_2__c = 1,Bonus_Description_2__c = 'Per Head Bonus (PHB)');       
        Insert univ; 
        
        /* 2nd Declare all Variables */      
        
        StudentApplicationClass.PersonalInformation PI = new StudentApplicationClass.PersonalInformation();
        PI.agentID 			= '001';
        PI.firstName        = 'First';
        PI.lastName         = 'Last';
        PI.email            = 'Email@example.com';
        PI.gender           = 'Female';
       // PI.DOB              = '2018-11-20';
        	PI.DOB 				= '09/05/1991';
       						
        PI.homeTelephone    = '1234567890';
        PI.middleName       = 'Middle';
        PI.maritalStatus    = 'Single';
        PI.mobile           = '9003036399';
        PI.city             = 'Bangalore';
        PI.passportNo       = 'BKBPA6662C';
        PI.accountSource    = 'Call';
        
        StudentApplicationClass.studyInterest SI = new StudentApplicationClass.studyInterest();
        SI.countryInterestedIn      = 'Canada';
        SI.interestedFieldOfStudy   = 'Engineering';
        SI.preferredUniversity      =  univ.ID;
        
        StudentApplicationClass.personalAddressInformation PAI = new StudentApplicationClass.personalAddressInformation();
        PAI.personalAddressLine     = '4,BuckingHam Palace Road';
        PAI.personalCity            = 'Westminster';
        PAI.personalCountry         = 'United Kingdom';
        PAI.personalZipcode         = 'SW1A 1AA';
        
        StudentApplicationClass.correspondenceAddressInformation CAI = new StudentApplicationClass.correspondenceAddressInformation();
        CAI.isCheck                       = True;
        CAI.correspondenceAddressLine     = '4,BuckingHam Palace Road';
        CAI.correspondenceCity            = 'Westminster';
        CAI.correspondenceCountry         = 'United Kingdom';
        CAI.correspondenceZipcode         = 'SW1A 1AA';
        
        StudentApplicationClass.emergencyContactPerson ECP = new StudentApplicationClass.emergencyContactPerson();
        ECP.emergencyContactPersonName  = 'Andrew';
        ECP.emergencyNumber             = '1234567890';
        ECP.emergencyCoverType          = 'Single';
        ECP.emergencyEmail              = 'Andrew@Emergency.com';
        ECP.firstLanguage               = 'English';
        
        StudentApplicationClass.Qualification  quali = new StudentApplicationClass.Qualification();
        quali.courseName    = 'MCA';
        quali.startedMonth  =  'April';
        quali.startedYear   = '2018';
        quali.finishedMonth = 'April';
        quali.finishedYear  = '2020';
        quali.language      = 'English UK';
        quali.country       = 'UK';
        quali.documentId    = documentObj.Id;
        
        
        StudentApplicationClass.educationalQualification EQ = new StudentApplicationClass.educationalQualification();
        EQ.englishProficiency      = 'Average';
       // EQ.testDate                = '2018-11-20';
       EQ.testDate                = '05/06/2018';
        EQ.ieltsScore			   =  '12.40';		
        EQ.educationQualification  = 'Postgraduate';
        EQ.qualifications          = new Map<String,StudentApplicationClass.Qualification>{'Postgraduate' => quali};            
          
        /* 1st Create Instance with Appication Class */
        
        StudentApplicationClass.Application app = new StudentApplicationClass.Application();
        app.personalInformation              = PI;
        app.studyInterest                    = SI;
        app.personalAddressInformation       = PAI;
        app.correspondenceAddressInformation = CAI;
        app.emergencyContactPerson           = ECP;
        app.educationalQualification         = EQ;
                
        /* Calling all Methods in Apex Class */
        StudentApplicationClass.isEmailExisting('Email@example.com');
        StudentApplicationClass STA = new StudentApplicationClass();
        STA.getpickvalues();
        STA.receiveInput();
        STA.removeInput();
        StudentApplicationClass.getCountryInterestedIn();
        StudentApplicationClass.getEducationPickValues();
        StudentApplicationClass.getExistingUniversities();
        StudentApplicationClass.saveApplication(app);             
    }
}